Please give me a zero on this assignment: CS170::ListLab::List Class Reference
CS170::ListLab::List Class Reference
Single-linked list class for CS170 labs.
#include <List.h>
Public Member Functions
void AddToEnd (int value)
Create and add a new node to the end of the given linked list.
void AddToFront (int value)
Create a new node and put it in the front of the given list.
int Count () const
Calculate how many nodes are in the incoming linked list.
Node * FindItem (int value) const
Finds an item and returns the node that contains it.
void Insert (int value, int position)
Inserts a new node at the specified position.
void Delete (int value)
Deletes a node with the specified value (first occurrence only)
void Concat (const List &Source)
Concatenates two lists.
void Delete (const List &Items)
Deletes all of the values in the list that are in Items.
void Insert (int value)
Inserts a new node in the correct position (sorted small to large).
void Merge (List &rhs)
Takes a sorted list and merges it into the list.
Private Member Functions
Node * MakeNode (int value) const
Make a new node to be added to the linked list.
void FreeList ()
Free all nodes in a given list.
Private Attributes
Node * head_
Pointer to the front of the list.
Friends
std::ostream & operator<< (std::ostream &os, const List &rhs)
Displays the list.
Detailed Description
Single-linked list class for CS170 labs.
Definition at line 43 of file List.h.
Member Function Documentation
void CS170::ListLab::List::AddToEnd (int value)
Create and add a new node to the end of the given linked list.
Parameters
value Value to be put in the new node.
Definition at line 127 of file List.cpp.
References head_, MakeNode(), and CS170::ListLab::Node::next.
Referenced by Concat().
     {
         /* new node to be added to the list */
       struct Node *holder = MakeNode(value);
       Node *list = head_;
         /* if the new node had memory allocated corectly */
       if (holder != 0)
       {
           /* if the list is not empty */
         if(list != 0)
         {
             /* while not at the end of the list */
           while (list->next != 0)
           {
               /* move to next node in the list */
             list = list->next;
           }
           /* add the new lode to the list */
           list->next = holder;
         }
         /* if the list is empty */
         else
         {
             /* set the list to be the new node */
           head_ = holder;
         }
       }
     }
void CS170::ListLab::List::AddToFront (int value)
Create a new node and put it in the front of the given list.
Parameters
value Value to be put in the new node.
Definition at line 169 of file List.cpp.
References head_, MakeNode(), and CS170::ListLab::Node::next.
Referenced by Insert().
     {
         /* make a new node and allocate momory for it */
       struct Node *holder = MakeNode(value);
       Node *list = head_;
         /* if the new node memory was successfully allocated */
       if (holder != 0)
       {
           /* set next for the new node to the passed in list */
         holder->next = list;
       }
         /* make the new node the start of the list */
       head_ = holder;
     }
void CS170::ListLab::List::Concat (const List & Source)
Concatenates two lists.
Parameters
Source List of nodes to add to the end of the list.
Definition at line 340 of file List.cpp.
References AddToEnd(), head_, CS170::ListLab::Node::next, and CS170::ListLab::Node::number.
     {
       Node *second = Source.head_; // Pointer to walk the list
         // While there is a list to walk through
       while(second->next != 0)
       {
           // Add the node to the end of the list and step to the next
         AddToEnd(second->number);
         second = second->next;
       }
         // Add the last node to the list
       AddToEnd(second->number);
     }
int CS170::ListLab::List::Count () const
Calculate how many nodes are in the incoming linked list.
Returns
Number of nodes in the list
Definition at line 102 of file List.cpp.
References head_, and CS170::ListLab::Node::next.
     {
       int count = 0; // Number of nodes in the list
       Node *list = head_;
       while (list != 0)
       {
         count++;
         list = list->next;
       }
       return count;
     }
void CS170::ListLab::List::Delete (int value)
Deletes a node with the specified value (first occurrence only)
Parameters
value Value to be deleted from the list.
Definition at line 292 of file List.cpp.
References head_, CS170::ListLab::Node::next, and CS170::ListLab::Node::number.
Referenced by Delete().
     {
         // If the list is empty
       if (head_ == NULL)
       {
         return;
       }
       Node *list = head_; // Pointer to walk the list
       if (list->number == value)
       {
         head_ = head_->next; // Set the front of the list to the next node
         delete list;       // Delete the node
         return;
       }
         // While there is more items in the list
       while (list->next->number != value && list->next->next != 0)
       {
           // Move to the next node
         list = list->next;
       }
       if (list->next->number == value)
       {
         Node *holder = list->next; // Pointer to the element to be deleted
             // Disconect the node to be deleted from the list
         list->next = list->next->next;
         holder->next = 0;
           // Delete the node
         delete holder;
       }
     }
void CS170::ListLab::List::Delete (const List & Items)
Deletes all of the values in the list that are in Items.
Parameters
Items Second list full of values to remove.
Definition at line 366 of file List.cpp.
References Delete(), head_, CS170::ListLab::Node::next, and CS170::ListLab::Node::number.
     {
       Node *list = Items.head_; // Pointer to walk the passed in list
         // While there is a list to walk through
       while (list->next != 0)
       {
           // Delete the node(s) and step to the next node
         Delete(list->number);
         list = list->next;
       }
         // Delete the last value from the list
       Delete(list->number);
     }
Node * CS170::ListLab::List::FindItem (int value) const
Finds an item and returns the node that contains it.
Parameters
value Value that is being looked for in a node.
Returns
A node with the given value
Definition at line 198 of file List.cpp.
References head_, CS170::ListLab::Node::next, and CS170::ListLab::Node::number.
     {
       Node *list = head_; /* pointer to the next node in the list */
         /* while there are still nodes in the list */
       while (list != 0)
       {
           /* If the current node contains what is being looked for */
         if(list->number == value)
         {
           return list;
         }
         list = list->next;
       }
       return list;
     }
void CS170::ListLab::List::Insert (int value, int position)
Inserts a new node at the specified position.
Parameters
value Value to be put in the new node.
position Where in the list to put the new node.
Definition at line 250 of file List.cpp.
References AddToFront(), head_, MakeNode(), and CS170::ListLab::Node::next.
Referenced by Insert().
     {
         /* If the position is at the front, add the node and exit early */
       if (position == 0)
       {
         AddToFront(value);
         return;
       }
       int count = 1;      /* Track current position of the list */
       Node *list = head_; /* Pointer to walk the list           */
         /* While there is still a list to go through and not to position */
       while(count < position && list->next != 0)
       {
           /* Walk the list and increment the count */
         list = list->next;
         count++;
       }
         /* If the list did not end before getting to position */
       if (count == position)
       {
         struct Node *holder = MakeNode(value); /* New node for the list */
           /* Add the new node to the list */
         holder->next = list->next;
         list->next = holder;
       }
     }
void CS170::ListLab::List::Insert (int value)
Inserts a new node in the correct position (sorted small to large).
Parameters
value Value to be put in the new node.
Definition at line 392 of file List.cpp.
References AddToFront(), head_, Insert(), CS170::ListLab::Node::next, and CS170::ListLab::Node::number.
     {
         // If there is no list yet
       if(head_ == NULL)
       {
         AddToFront(value);
         return;
       }
       int position = 0;   // Track current list position
       Node *list = head_; // Pointer to walk the list
         // While there is a list to walk through
       while (list->next != 0)
       {
           // If the value is larger than the node
         if (list->number <= value)
         {
             // Increment to the next node
           list = list->next;
           ++position;
         }
           // If the value is smaller than the node, stop looking
         if (list->number >= value)
         {
           break;
         }
       }
         // Make sure the position is correct if at end of list
       if(list->number <= value)
       {
         ++position;
       }
       Insert(value, position);
     }
Node * CS170::ListLab::List::MakeNode (int value) const private
Make a new node to be added to the linked list.
Parameters
value value to put in the node.
Returns
Node for a linked list
Definition at line 86 of file List.cpp.
Referenced by AddToEnd(), AddToFront(), and Insert().
     {
         // The Node constructor sets the value, and sets next to 0.
       return new Node(value);
     }
void CS170::ListLab::List::Merge (List & rhs)
Takes a sorted list and merges it into the list.
Parameters
rhs Sorted list to merge into the list object.
Definition at line 441 of file List.cpp.
References head_, CS170::ListLab::Node::next, and CS170::ListLab::Node::number.
     {
       Node *leftList;
       Node *rightList;
         //If there is a list
       if(head_ != NULL)
       {
           //Setup a pointer to the first node of the left list. (left)
         leftList = head_;
       }
       else
       {
         head_ = rhs.head_;
         rhs.head_ = NULL;
         return;
       }
        //If a list was passed in
       if(rhs.head_ != NULL)
       {
           //Setup a pointer to the first node of the right list (right)
         rightList = rhs.head_;
       }
       else
       {
         return;
       }
         //Setup a pointer to point to the head of the new list
       Node *firstNew = NULL;
         //Setup a pointer to point to the tail of the new list
       Node *lastNew = NULL;
       //While both pointers (left and right) are pointing at a node
       while(leftList != NULL && rightList != NULL)
       {
           //If the left node is less than or equal to the right node,
         if(leftList->number <= rightList->number)
         {
             //Add the left node to the new list
           if(firstNew == NULL)
           {
               //Set the front and end of the list to the currant left node
             firstNew = leftList;
             lastNew = leftList;
           }
           else
           {
               //Append the left node to the end of the list
             lastNew->next = leftList;
               //Move the end of the list to the new end of the list
             lastNew = lastNew->next;
           }
           //Move the left pointer to the next node in the left list
           leftList = leftList->next;
         }
         //Else  (The left node is greater than the right node)
         else
         {
             //Add the right node to the new list
           if(firstNew == NULL)
           {
               //Set the front and end of the list to the currant right node
             firstNew = rightList;
             lastNew = rightList;
           }
           else
           {
               //Append the right node to the end of the list
             lastNew->next = rightList;
               //Move the end of the list to the new end of the list
             lastNew = lastNew->next;
           }
           //Move the right pointer to the next node in the right list
           rightList = rightList->next;
         }
       }
         //If the right side is empty and the left side still has nodes
       if(leftList != NULL)
       {
           //Add all of the nodes from the left side to the end of the new list
         lastNew->next = leftList;
       }
         //If the left side is empty and the right side still has nodes
       if(rightList != NULL)
       {
           //Add all of the nodes from the right side to the end of the new list
         lastNew->next = rightList;
       }
         // Update the heads of the lists to the new values.
       head_ = firstNew;
       rhs.head_ = NULL;
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const List & rhs) friend
Displays the list.
Parameters
os The stream being outputted to.
rhs The list that is being displayed.
Returns
The output stream.
Definition at line 557 of file List.cpp.
     {
       Node *list = rhs.head_; // Pointer to walk the list
         // While there is still list to walk
       while (list != 0)
       {
           //send the node to the os and step to the next node
         os << list->number << "   ";
         list = list->next;
       }
       return os;
     }
The documentation for this class was generated from the following files:
List.h
List.cpp